/**
 * Generates reference pages from the source of truth:
 *
 * - docs/components.md — from the built-in directive specs
 * - docs/errors.md     — from the diagnostic catalogue
 *
 *   node --conditions=source scripts/generate-docs.ts          (write)
 *   node --conditions=source scripts/generate-docs.ts --check  (fail if stale)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { builtinRegistry, DIAGNOSTIC_CODES } from '@markup-lang/core';
import { componentReference } from '@markup-lang/language-service';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const NOTICE = '<!-- Generated by scripts/generate-docs.ts — do not edit by hand. -->\n\n';

export function componentsPage(): string {
  return NOTICE + componentReference(builtinRegistry, { title: 'Component reference' });
}

export function errorsPage(): string {
  const groups: [string, string][] = [
    ['MU1', 'Syntax'],
    ['MU15', 'MarkUP Data'],
    ['MU2', 'Validation'],
    ['MU9', 'Internal'],
  ];
  let out = `${NOTICE}# Diagnostic reference\n\n`;
  out +=
    'Every problem MarkUP reports has a stable code. Tools can filter on codes; messages may improve between versions.\n\n';
  out +=
    'Severities are the defaults; a few diagnostics use a different severity in specific situations (for example, chart length mismatches are warnings).\n\n';
  const entries = Object.entries(DIAGNOSTIC_CODES);
  for (const [prefix, title] of groups) {
    const list = entries.filter(
      ([code]) => code.startsWith(prefix) && (prefix !== 'MU1' || !code.startsWith('MU15')),
    );
    if (list.length === 0) continue;
    out += `## ${title}\n\n| Code | Name | Severity | Meaning |\n|---|---|---|---|\n`;
    for (const [code, info] of list)
      out += `| \`${code}\` | ${info.name} | ${info.severity} | ${info.summary.replace(/\|/g, '\\|')} |\n`;
    out += '\n';
  }
  return out;
}

const pages: [string, () => string][] = [
  ['docs/components.md', componentsPage],
  ['docs/errors.md', errorsPage],
];

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const [file, generate] of pages) {
    const path = join(root, file);
    const content = generate();
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // Missing file counts as stale.
    }
    if (current === content) continue;
    if (check) {
      console.error(`${file} is out of date. Run npm run docs:generate.`);
      stale = true;
    } else {
      writeFileSync(path, content);
      console.log(`wrote ${file}`);
    }
  }
  if (stale) process.exitCode = 1;
}
